### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement mamimo (from versions: none)

### ISSUE THREAD

**Issue by entzyeung** [Garve/mamimo#1]
Hello Dr. Robert, I found your article very useful, thank you alot for the sharing.
By the way, I am trying to follow your steps in the article, and when I `pip install mamimo`, it shows me 2 errors, 
`ERROR: Could not find a version that satisfies the requirement mamimo (from versions: none)
ERROR: No matching distribution found for mamimo`
Do you know why is it?

**Comment by RobKuebler** [comment]
Hi!

Could you try updating your pip version? Because it works for me, I also tried another PC.
`python -m pip install --upgrade pip`

Good luck!

Best
Robert

**Comment by RobKuebler** [comment]
Hi!

This problem was solved by updating to Python 3.9+.

Best
Robert

**Comment by entzyeung** [comment]
> Hi!
> 
> Could you try updating your pip version? Because it works for me, I also tried another PC. `python -m pip install --upgrade pip`
> 
> Good luck!
> 
> Best Robert

yes, it works perfectly now, thank you Dr Garve!
