### ISSUE TITLE
code for plot graphic

### ISSUE THREAD

**Issue by raismartup** [Garve/mamimo#2]
Hi Sr.Garve

Congralutations for your project! It´s fantastic :)

Although it is not a question especially of the mamimo package, I would like to know if you could pass me the code to be able to represent the saturation and carryover effects of your article in towardsdatascienc:

**https://towardsdatascience.com/an-upgraded-marketing-mix-modeling-in-python-5ebb3bddc1b6**

Specifically these that I show below

![image](https://user-images.githubusercontent.com/107853548/180191313-fc701115-4ad9-4384-bbe4-93462c88a016.png)

![image](https://user-images.githubusercontent.com/107853548/180191375-9f22423c-f85e-4661-a01f-b2f6575a5d19.png)

I can't figure out how to get this data to plot the graph and check both fantastic effects shown here.

Thanks for your help :)

**Comment by RobKuebler** [comment]
Hello!

The first graphs are just the functions 1-exp(-a*x) where a is the best saturation parameter.

The second row is c^x where c is the best carryover value, and the x are the integers from 0to 5.

Hope that helps!

Best
Robert

**Comment by raismartup** [comment]
Hi again!

thank you for your reply :)

I had asked for the plot code because I can not get them to appear exactly the same because in the saturation I get the price for the Radio is 7700 and yet in the graph appears values of 15000. I don't know if at the end you are adding the amount of each x weeks or if it is an aggregate sum of each week. 

In the carryover graphs I don't know how you get this %. Do you do the percentage every 5 lags? or how? 

Thank you for your kindness :)

Best
Rai

**Comment by RobKuebler** [comment]
Hi!

Well, you can decide the price range however you want. I chose 0 to 15000, but you can also make this range larger or smaller. I'm really just plotting 1-exp(-a*x) there, nothing more, nothing less. If a=0.0001, just plot `1-np.exp(-0.0001*x)` from x=0 to 15000, for example.

In the carryover, just do `0.5**np.arange(5)` and plot this as a bar chart if you wanna plot the carryover for 5 days, with a strength of 0.5. Then just format the y-Axis to percentages, and you are done.

Best
Robert

**Comment by raismartup** [comment]
Hi!

I think I understood perfectly the carriover graph :)

To finish, I understand that in the graphs of Baaners and Radio only appear 100% because the length in the optimization of hyperparameters is 0 no? understanding that only the advertising has only effect the first week

` (0.5**np.arange(5))* np.array([1, 0, 0, 0, 0]))  ` in the case length = 0
` (0.5**np.arange(5))* np.array([1, 1, 1, 0, 0]))  ` in the case length = 2

thank you very much :)

**Comment by RobKuebler** [comment]
On day 0, 100% of the spending effect is still in place. On day 1, only 100%*50%=50%. At day 2 only 100%*50%*50%=25%, etc. That's all that graphic says.

**Comment by raismartup** [comment]
Thank for you help! :)
