### ISSUE TITLE
Unable to Install mamimo

### ISSUE THREAD

**Issue by Anagha-colpal** [Garve/mamimo#5]
As a first step, I'm unable to install mamimo library. I'm getting below error:

**Error** 
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement mamimo
ERROR: No matching distribution found for mamimo
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement mamimo
ERROR: No matching distribution found for mamimo

**Here is my Python Version Details**
/opt/anaconda3/bin/python
3.8.8 (default, Apr 13 2021, 12:59:45) 
[Clang 10.0.0 ]
sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)

**Comment by RobKuebler** [comment]
Hi!

Try Python version 3.9 or higher, then it should work!

Best
Robert
