### ISSUE TITLE
Package import error

### ISSUE THREAD

**Issue by larun1916** [Garve/mamimo#6]
I am getting the below error while running the code. 
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/131447358/233601801-adb1bcf5-d57b-4993-a908-a153639b41eb.png">

**Comment by amanabdullayev** [comment]
there was a typo while importing **sklearn** function =>_`OneToOneFeatureMixin`, this actually should be without an underscore: `OneToOneFeatureMixin`, which is required for **carryover and saturatio**n classes. Fixed this import issue in #7 and created a PR.

**Comment by RobKuebler** [comment]
Hello! I uploaded the new version to pypi now. A pip install mamimo==0.4.3 should fix it! Thanks a lot for reporting and fixing it :) it was still based on an older version of scikit-learn (1.1.2), and there, it still contained an underscore.
